jobs:
- name: btrfs-tools
  serial: true
  public: true
  plan:
  - get: concourse
  - task: build
    file: concourse/ci/build-btrfs-tools.yml
  - get: deployments
  - task: bump-blob
    input_mapping:
      blob-dir: btrfs-tools
    file: concourse/ci/bump-blob.yml
    params:
      BLOB_NAME: btrfs-tools
      BLOB_VERSION: 4.4
      BLOB_DESTINATION: btrfs
      BOSH_PRIVATE_CONFIG: {{bosh-private-config}}
  - put: concourse
    params: {repository: bumped-concourse, rebase: true}

resources:
- name: concourse
  type: git
  source:
    uri: git@github.com:concourse/concourse.git
    branch: develop
    private_key: {{concourse-repo-private-key}}
